spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-nx-api
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
#    hikari:
#      jdbc-url:  jdbc:postgresql://localhost:5432/spring-nx-api
#      username: postgres
#      password: example
#      driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
